//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.27 at 12:18:46 PM EEST 
//
package net.freelabs.maestro.core.schema;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.*;

/**
 * <p>
 * Java class for containerEnvironment complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="containerEnvironment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="host_port" type="{}port"/>
 *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "containerEnvironment", propOrder = {
    "host_port",
    "any",
    "host_IP"
})
public class ContainerEnvironment {

    @XmlElement(name = "host_port")
    protected int host_port;
    @XmlAnyElement
    protected List<Element> any;
    @XmlElement
    protected String host_IP;

    public String getHost_IP() {
        return host_IP;
    }

    public void setHost_IP(String host_IP) {
        this.host_IP = host_IP;
    }

    private Map<String, String> getAnyElemsExceptEnvMappings() {
        Map<String, String> elemsMap = new HashMap<>();
        for (Element elem : getAny()) {
            String elemName = elem.getTagName();
            String elemValue = elem.getTextContent().trim();
            // check if this is not a mapping from one env var to another
            if (!isEnvMapping(elemValue)) {
                // add elem to map
                elemsMap.put(elemName, elemValue);
            }
        }
        return elemsMap;
    }

    private Map<String, String> getAnyElemsOnlyEnvMappings() {
        Map<String, String> elemsMap = new HashMap<>();
        for (Element elem : getAny()) {
            String elemName = elem.getTagName();
            String elemValue = elem.getTextContent().trim().toUpperCase();
            // check if this is not a mapping from one env var to another
            if (isEnvMapping(elemValue)) {
                // extract value
                elemValue = elemValue.substring(elemValue.indexOf("{")+1, elemValue.indexOf("}"));
                // add elem to map
                elemsMap.put(elemName, elemValue);
            }
        }
        return elemsMap;
    }

    /**
     * Creates the container environment.
     *
     * @return a map with the environment variables and their values that make
     * up the container environment.
     */
    public Map<String, String> createEnvMap() {
        Map<String, String> envMap = new HashMap<>();
        // add class fields to map
        envMap.put("host_port", String.valueOf(host_port));
        envMap.put("host_ip", host_IP);
        // add any elements to map
        envMap.putAll(getAnyElemsExceptEnvMappings());

        return envMap;
    }

    private boolean isEnvMapping(String value) {
        return value.startsWith("${") && value.endsWith("}");
    }

    /**
     *
     * @return a map with the declared environment variable mappings, that is
     * mappings of environment variable names to other env var names.
     */
    public Map<String, String> createEnvMappings() {
        Map<String, String> envMap = new HashMap<>();
        envMap.putAll(getAnyElemsOnlyEnvMappings());
        return envMap;
    }

    public boolean areAnyElemsStrings() {
        boolean success = true;

        for (Element elem : getAny()) {
            NodeList nodeList = elem.getChildNodes();
            if (nodeList.getLength() != 0) {
                success = false;
                break;
            }
        }
        return success;
    }

    /**
     * Gets the value of the host_Port property.
     *
     */
    public int getHost_Port() {
        return host_port;
    }

    /**
     * Sets the value of the host_Port property.
     *
     */
    public void setHost_Port(int value) {
        this.host_port = value;
    }

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Element }
     *
     *
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

}
